randomseed: [0]   # None == random
Action: [0,1]   # 0:Train,   1: Test
device: "cuda"
nmul: 16

forcing_path: 'F:\code_repos\water\data\Camels\camels_671_2023113_prep\camels_671_dp_20231113.feather'
attr_path: 'F:\code_repos\water\data\Camels\camels_671_2023113_prep\attr_camels_all_sep14_2023.feather'
output_model: 'F:\code_repos\water\data\model_runs\PGML_STemp_results\671_sites\dynamic' 

## Train model from a checkpoint: 
# saved_epoch: 40
# checkpoint_path: 'F:\code_repos\water\data\model_runs\PGML_STemp_results\671_sites\dynamic\LSTM_HBV_E50_R365_B100_H256_tr1980_1995_n16_0\parBETA_parBETAET_'

## Neural network configuration.
NN_model_name: "LSTM"   # it can be "MLP", "LSTM" too.
loss_function: "RmseLoss_flow_comb"      # "RmseLoss_flow_temp", "RmseLoss_flow_temp_BFI",  "RmseLoss_flow_temp_BFI_PET", "RmseLoss_flow_comb"  RmseLoss_BFI_temp  NSEsqrtLoss_flow_temp
loss_function_weights:
    w1: 11.0      # w1: flow loss weight (11.0), for RmseLoss_BFI_temp(w1=0.05, w2=1.0)
    w2: 1.0
# USGS code.
target: ["00060_Mean"]    #, "00010_Mean"]#, "BFI_AVE"] #, "BFI_AVE", "PET"]     
tRange: [19800101, 20101001] # Entire train-test period 
t_train: [19801001, 19951001]
t_val: [20101001, 20111001]
t_test: [19951001, 20101001]
warm_up: 365
rho: 365
batch_size: 100
EPOCHS: 50
hidden_size: 256
dropout: 0.5
saveEpoch: 2
no_basins: 25
varT_NN: ['prcp(mm/day)', 'tmean(C)', 'PET_hargreaves(mm/day)']
varC_NN: [
 'p_mean', 'pet_mean', 'p_seasonality', 'frac_snow', 'aridity',
 'high_prec_freq', 'high_prec_dur', 'low_prec_freq', 'low_prec_dur',
 'elev_mean', 'slope_mean', 'area_gages2', 'frac_forest', 'lai_max',
 'lai_diff', 'gvf_max', 'gvf_diff', 'dom_land_cover_frac',
 'dom_land_cover', 'root_depth_50', 'soil_depth_pelletier',
 'soil_depth_statsgo', 'soil_porosity', 'soil_conductivity',
 'max_water_content', 'sand_frac', 'silt_frac', 'clay_frac',
 'geol_1st_class', 'glim_1st_class_frac', 'geol_2nd_class',
 'glim_2nd_class_frac', 'carbonate_rocks_frac', 'geol_porostiy',
 'geol_permeability'
]

## Temperature model configuration.
temp_model_name: "None"
routing_temp_model: True
res_time_type: "SNTEMP"
res_time_lenF_ssflow: 30   #60
res_time_lenF_bas_shallow: 180 #
res_time_lenF_gwflow: 730 #
res_time_lenF_srflow: 1
lat_temp_adj: True
shade_smoothening: False
frac_smoothening_mode: False
frac_smoothening_gw_filter_size: 40
frac_smoothening_ss_filter_size: 40
STemp_default_emissivity_veg: 0
STemp_default_albedo: 0.1
STemp_default_delta_Z: 1.0       # for streambed conduction
params_water_density: 1000
params_C_w: 4184    # J/kg. K
NEARZERO: 1e-5
Epan_coef: 1.0
initial_values_shade_fraction: 0.1
varT_temp_model: ['tmax(C)', 'tmin(C)',  "ccov", "PET_hargreaves(mm/day)",
              'prcp(mm/day)', 'vp(Pa)', "srad(W/m2)", 'tmean(C)']    #'dayl(s)',  , "dayofyear", "t_monthly(C)",
varC_temp_model: ["DRAIN_SQKM", "stream_length_square", 'SLOPE_PCT',
              'ELEV_MEAN_M_BASIN']       #  "area_gages2",   "RIP100_FOREST", "lat"   'PPTAVG_BASIN',
dyn_params_list_temp: ["width_coef_pow", "w1_shade"]

## Hydro model configuration.
hydro_model_name: ['HBV', 'SACSMA_with_snow', 'marrmot_PRMS']  # it can be marrmot_PRMS, HBV, SACSMA, SACSMA_with_snow, marrmot_PRMS_gw0 or None -> "None" means no hydrology model
varT_hydro_model: ['prcp(mm/day)', 'tmean(C)', 'tmax(C)', 'tmin(C)', "PET_hargreaves(mm/day)"] #, "t_monthly(C)", 'dayl(s)', "dayofyear"]    # , "pet_nldas"
varC_hydro_model: ['DRAIN_SQKM', "lat"]    # "area_gages2"
routing_hydro_model: True
dyn_params_list_hydro: []  #['parBETA', 'parBETAET']   #["scx", "cgw", "alpha", "tt"]   # parTT

## PET model configurations
potet_module: "dataset" # "potet_hamon"  # "potet_hargreaves" , "dataset" -> Hamon is not ready beacause of lack of monthly coef
potet_dataset_name: "PET_hargreaves(mm/day)"  #"PET_hargreaves(mm/day)" # if "potet_module" == "dataset"
