help:
  app_name: hydro-multimodel
  header: == ${hydra.help.app_name} ==
  template: |-
    ${hydra.help.header}

    Multimodel framework developed by Leo Lonzarich, w/ contributions from Tadd Bindas, Farshid Rahmani, et al.

    ${hydra.help.footer}
  footer: |-
    Powered by Hydra (https://hydra.cc)
    Use --hydra-help to view Hydra specific help
job:
  name: ${name}
  chdir: False # Changes working dir to 'run' dir.
run:
  dir: ${hydra:runtime.cwd}/runs/logs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
sweep:
  dir: multirun
  subdir: ${hydra.job.override_dirname}
