## General Config -------------------------------#
mode: test_bmi    # train, test, train_test, train_wtnn_only
ensemble_type: none    # none, frozen_pnn, free_pnn
use_checkpoint: False    # See bottom

random_seed: 0
device: cuda
gpu_id: 2

train:
    start_time: 1980/10/01
    end_time: 1995/10/01
test:
    start_time: 1995/10/01
    end_time: 2010/10/01

batch_basins: 25

name: hmm1.1-${observations.name}
# data_dir: /Users/leoglonz/Desktop/water/data
# data_dir: F:\code_repos\water\data
data_dir: /data/lgl5139/hydro_multimodel/dPLHydro_multimodel/runs
output_dir: ${data_dir}/${observations.name}/saved_models/ #debug_2


## BMI Config -------------------------------#
time_step_delta: 1



## Model Config -------------------------------#
pnn_model: LSTM    # LSTM, MLP
hydro_models: [HBV]    # HBV, marrmot_PRMS, SACSMA_with_snow
dyn_hydro_params:
    HBV: []    # parBETA, parBETAET
    SACSMA: []
    PRMS: []

routing_hydro_model: True
pet_module: dataset    # dataset, potet_hamon, potet_hargreaves
pet_dataset_name: PET_hargreaves(mm/day)
target: ['00060_Mean']    # 00060_Mean, 00010_Mean, BFI_AVE, PET

loss_function: RmseLoss_flow_comb
loss_function_weights:
    w1: 11.0
    w2: 1.0

nmul: 16
warm_up: 365
rho: 365
batch_size: 100
epochs: 50
hidden_size: 256
dropout: 0.5
nearzero: 1e-5

save_epoch: 10

weighting_nn:
    dropout: 0.5
    hidden_size: 256
    method: sigmoid
    loss_function: RmseLoss_flow_comb
    loss_function_weights:
        w1: 11.0
        w2: 1.0
    loss_factor: 15
    loss_lower_bound: 0.95
    loss_upper_bound: 1.05


## Model Checkpoints -------------------------------#
checkpoint:
    start_epoch: 11
    HBV: /data/lgl5139/hydro_multimodel/dPLHydro_multimodel/runs/camels_671_dp/saved_models/free_pnn/LSTM_E50_R365_B100_H256_n2_0/static_para/HBV_/HBV_model_Ep10.pt
    marrmot_PRMS: /data/lgl5139/hydro_multimodel/dPLHydro_multimodel/runs/camels_671_dp/saved_models/free_pnn/LSTM_E50_R365_B100_H256_n2_0/static_para/HBV_/marrmot_PRMS_model_Ep10.pt
    SACSMA_with_snow: /data/lgl5139/hydro_multimodel/dPLHydro_multimodel/runs/camels_671_dp/saved_models/free_pnn/LSTM_E50_R365_B100_H256_n2_0/static_para/HBV_/SACSMA_with_snow_model_Ep10.pt
    weighting_nn: /data/lgl5139/hydro_multimodel/dPLHydro_multimodel/runs/camels_671_dp/saved_models/free_pnn/LSTM_E50_R365_B100_H256_n2_0/static_para/HBV_/wtNN_model_model_Ep10.pt


## Observations -------------------------------#
observations:
    name: gages2_50
    gage_info: None
    forcing_path: /scratch/fzr5082/PGML_STemp_results/inputs/dataset_20240331/forcing_50_20240331.feather
    attr_path: /scratch/fzr5082/PGML_STemp_results/inputs/dataset_20240331/attr50.feather

    var_t_nn: [
        'prcp(mm/day)',
        'tmean(C)',
        'dayl(s)',
        'PET_hargreaves(mm/day)'
    ]

    var_c_nn: [
        'ELEV_MEAN_M_BASIN',
        'ELEV_STD_M_BASIN',
        'SLOPE_PCT',
        'DRAIN_SQKM',
        'NDAMS_2009',
        'MAJ_NDAMS_2009',
        'FRAGUN_BASIN',
        'FORESTNLCD06',
        'AWCAVE',
        'PERMAVE',
        'BDAVE',
        'ROCKDEPAVE',
        'CLAYAVE',
        'SILTAVE',
        'SANDAVE',
        'HGA',
        'HGB',
        'HGC',
        'HGVAR',
        'HGD',
        'PPTAVG_BASIN',
        'SNOW_PCT_PRECIP',
        'PRECIP_SEAS_IND',
        'T_AVG_BASIN',
        'T_MAX_BASIN',
        'T_MAXSTD_BASIN',
        'RH_BASIN',
        'GEOL_REEDBUSH_DOM_PCT',
        'GEOL_REEDBUSH_DOM',
        'HIRES_LENTIC_PCT',
        'PERDUN',
        'PERHOR',
        'RIP100_FOREST'
    ]

    var_t_hydro_model: [
        'prcp(mm/day)',
        'tmean(C)',
        'tmax(C)',
        'tmin(C)',
        'PET_hargreaves(mm/day)'
    ]

    var_c_hydro_model: [
        'DRAIN_SQKM',
        'lat'
    ]