# Experiment-- ---------------------------------------------------------------------
name: ${name}
save_path: ${hydra:run.dir}
tensorboard_dir: ${hydra:run.dir}
#checkpoint: /data/tkb5476/projects/dMC-dev/runs/trained_models/2024-02-19_15-05-52_5_epoch_training_merit_global_v1.1/dMCv0.1-gages_3000-merit_global_v1.1_epoch_6_mb_0.pt
#checkpoint: /data/tkb5476/projects/dMC-dev/runs/dMCv0.1-gages_3000-dpl_v3/2024-01-31_23-21-22_rho_168_1_epoch/dMCv0.1-gages_3000-dpl_v3_model_state_2_mini_batch_0.pt
#checkpoint: /data/tkb5476/projects/dMC-dev/runs/susquehanna_benchmark/2024-01-28_11-02-44_14_epoch_run/susquehanna_benchmark_mlp_14.pt