# Data --------------------------------------------------------------------------
attributes:
  - len
  - len_dir
  - sinuosity
  - slope
  - stream_drop
  - uparea

name: grdc
batch_size: 2
dropout_threshold: -1
gage_locations: ${data_dir}/observations/large_basin_74.csv
minimum_zones: 3
observation_source: grdc
observations: ${data_dir}/observations/grdc_streamflow
streamflow_version: merit_global_v1.1
shuffle: False
time:
  start: 1985/01/01
  end: 1986/01/01
  origin_start_date: 1980/01/01
zarr:
  edges: ${marquette_data_dir}/MERIT/zarr/graph/edges/
  gage_coo_indices: ${marquette_data_dir}/MERIT/zarr/gage_coo_indices
  HUC_TM: ${marquette_data_dir}/MERIT/zarr/TMs/PFAF_
  MERIT_TM: ${marquette_data_dir}/MERIT/zarr/TMs/MERIT_FLOWLINES_
  q_prime: ${marquette_data_dir}/MERIT/zarr/q_prime
  streamflow: ${marquette_data_dir}/streamflow/zarr/${dataset.streamflow_version}/