# Data --------------------------------------------------------------------------
attributes:
  - len
  - len_dir
  - sinuosity
  - slope
  - stream_drop
  - uparea

name: gages_3000
batch_size: 100
chunk_size: 365
dropout_threshold: 20000
gage_locations: ${data_dir}/observations/gages_3000_merit_info.csv
minimum_zones: 3
observation_source: zarr_usgs
#observation_source: usgs
observations: ${data_dir}/observations/zarr/gages_9000
#observations: ${data_dir}/observations/gages_streamflow
#streamflow_version: dpl_v3
streamflow_version: merit_global_v1.1
rho: 182
shuffle: True
time:
  start: 1981/10/01
  end: 1995/09/30
#  origin_start_date: 1980/01/01
zarr:
  edges: ${marquette_data_dir}/zarr/graph/edges/
  gage_coo_indices: ${marquette_data_dir}/zarr/gage_coo_indices
  HUC_TM: ${marquette_data_dir}/zarr/TMs/PFAF_
  MERIT_TM: ${marquette_data_dir}/zarr/TMs/MERIT_FLOWLINES_
  streamflow: ${marquette_data_dir}/streamflow/zarr/${dataset.streamflow_version}/