defaults:
  - _self_
  - observations: gages2_50
  - hydra: settings


## Config -------------------------------#
mode: train
nn_model: LSTM
hydro_models: ['HBV', 'SACSMA_with_snow', 'marrmot_PRMS']
ensemble_type: ensemble
freeze_param_nn: False

dyn_hydro_params:
  HBV: ['parBETA', 'parBETAET']
  SACSMA: ['parTT']
  PRMS: []


## Config for all differentiable hydrology models ------#
random_seed: 0
device: cuda
gpu_id: 0

routing_hydro_model: True
forcings: gages2_50
potet_module: dataset
potet_dataset_name: PET_hargreaves(mm/day)
target: ['00060_Mean']

loss_function: RmseLoss_flow_comb
loss_function_weights:
    w1: 11.0
    w2: 1.0

train:
    start_time: 1980/10/01
    end_time: 1995/10/01
test:
    start_time: 1995/10/01
    end_time: 2010/10/01

nmul: 16
warm_up: 365
rho: 365
batch_size: 100
epochs: 50
hidden_size: 256
dropout: 0.5
nearzero: 1e-5

weighting_nn:
    wdropout: 0.5
    hidden_size: 256
    loss_factor: 15
    method: sigmoid
    target: ['00060_Mean']
    loss_function: RmseLoss_flow_comb
    loss_function_weights:
        w1: 11.0
        w2: 1.0

n_basins: 25
save_epoch: 1

data_dir: /Users/leoglonz/Desktop/water/data
# data_dir: F:\code_repos\water\data

name: hmm0.3.0-${forcings}
output_dir: ${data_dir}/model_runs/hydro_multimodel_results/${forcings}/debugging
