defaults:
    - _self_
    - observations: camels_671_dp # gages2_50, camels_671_dp
    # - load_models: load_models_config
    - hydra: settings


## Config -------------------------------#
mode: train_wts_only #train_wts_only
nn_model: LSTM
hydro_models: ['HBV', 'SACSMA_with_snow', 'marrmot_PRMS']
ensemble_type: ensemble
freeze_para_nn: False

dyn_hydro_params:
    HBV: []
    SACSMA: []
    PRMS: []


## Config for all differentiable hydrology models ------#
random_seed: 0
device: cuda
gpu_id: 5

routing_hydro_model: True
forcings: camels_671_dp
potet_module: dataset
potet_dataset_name: PET_hargreaves(mm/day)
target: ['00060_Mean']

loss_function: RmseLoss_flow_comb
loss_function_weights:
    w1: 11.0
    w2: 1.0

train:
    start_time: 1980/10/01
    end_time: 1995/10/01
test:
    start_time: 1995/10/01
    end_time: 2010/10/01

nmul: 16
warm_up: 365
rho: 365
batch_size: 100
epochs: 50
hidden_size: 256
dropout: 0.5
nearzero: 1e-5

weighting_nn:
    dropout: 0.5
    hidden_size: 256
    method: sigmoid
    target: ['00060_Mean']
    loss_function: RmseLoss_flow_comb
    loss_factor: 15
    loss_lower_bound: 0.95
    loss_upper_bound: 1.05
    loss_function_weights:
        w1: 11.0
        w2: 1.0

n_basins: 25
save_epoch: 1

# data_dir: /Users/leoglonz/Desktop/water/data
# data_dir: F:\code_repos\water\data
data_dir: /data/lgl5139/hydro_multimodel/dPLHydro_multimodel/runs

name: hmm0.3.0-${forcings}
output_dir: ${data_dir}/${forcings}/saved_models/debugging_may5_final

## Use pre-trained hydro models to only train weighting LSTM.
# HBV: /data/lgl5139/hydro_multimodel/model_runs/_hydro_models/static/LSTM_HBV_E50_R365_B100_H256_tr1980_1995_n16_0/model_Ep50.pt
# marrmot_PRMS: /data/lgl5139/hydro_multimodel/model_runs/_hydro_models/static/LSTM_marrmot_PRMS_E50_R365_B100_H256_tr1980_1995_n16_0/model_Ep50.pt
# SACSMA_with_snow: /data/lgl5139/hydro_multimodel/model_runs/_hydro_models/static/LSTM_SACSMA_with_snow_E50_R365_B100_H256_tr1980_1995_n16_0/model_Ep50.pt
HBV: /data/lgl5139/hydro_multimodel/model_runs/May1/HBV_model_Ep50.pt
marrmot_PRMS: /data/lgl5139/hydro_multimodel/model_runs/May1/marrmot_PRMS_model_Ep50.pt
SACSMA_with_snow: /data/lgl5139/hydro_multimodel/model_runs/May1/SACSMA_with_snow_model_Ep50.pt
