##### This is YAML file contains settings for the PRMS
##### model used in the ensemble. 
##### Defaults are set in accordance with those used to achieve the MHPI
##### Benchmarking results for the 671 CAMELs basins over 15-year train/test periods
##### Make sure file paths are correct as they are individual to your machine.


randomseed: [0]   # None means random
Action: [1]   # 0:Train,   1: Test
device: "cuda"
nmul: 16  # For parallelization.

### Directories of forcings, attributes, and output.
## For debugging, only 50 sites.
# forcing_path: 'D:\\data\\PGML_STemp_Data\\50_sites\\forcing_50_20231113.feather'
# attr_path: 'D:\\data\\PGML_STemp_Data\\50_sites\\attr50.feather'
# output_model: 'D:\\data\\model_runs\\PGML_STemp_results\\models\\PRMS_SNTEMP\\debug'

## For full-scale test with temperature, 415 basins.
# forcing_path: 'D:\\data\\PGML_STemp_Data\\415_sites\\forcing_415_20231113.feather'
# attr_path: 'D:\\data\\PGML_STemp_Data\\415_sites\\attr_415_tmean_ccov.feather'
# output_model: 'D:\\data\\model_runs\\PGML_STemp_results\\models\\PRMS_SNTEMP\\415_sites'

## For full-scale test w/o tmp, 671 basins. Use "dp" attributes to
## emulate Dapeng paper resuls.
# forcing_path: 'D:\\data\\Camels\\camels_671_2023113_prep\\camels_671_dp_20231113.feather'
# attr_path: 'D:\\data\\Camels\\camels_671_2023113_prep\\attr_camels_all_sep14_2023.feather'
# output_model: 'D:\\data\\model_runs\\PGML_STemp_results\\models\\PRMS_SNTEMP\\671_sites_dp'

forcing_path: '/content/Camels/camels_671_2023113_prep/camels_671_dp_20231113.feather'
attr_path: '/content/Camels/camels_671_2023113_prep/attr_camels_all_sep14_2023.feather'
output_model: '/content/drive/MyDrive/Colab/data/model_runs/PGML_STemp_results/models/PRMS_SNTEMP/671_sites_dp'


## If you have a checkpoint file for a previous run, set the path to directory here. 
# saved_epoch corresponds to the .pt model save file, and is the last epoch 
# to have been fully run and saved (i.e., you now want to run saved_epoch+1). 
# saved_epoch: 10
# checkpoint_path: 'D:\\data\\model_runs\\PGML_STemp_results\\models\\PRMS_SNTEMP\\671_sites\\LSTM_marrmot_PRMS_E50_R365_B100_H256_tr1980_1995_n2_0'


## neural network configuration.
NN_model_name: "LSTM"   # it can be "MLP", "LSTM" too.
loss_function: "RmseLoss_flow_comb"      # "RmseLoss_flow_temp", "RmseLoss_flow_temp_BFI",  "RmseLoss_flow_temp_BFI_PET", "RmseLoss_flow_comb"  RmseLoss_BFI_temp
loss_function_weights (for process-based, ):
    w1: 11.0      # w1: flow loss weight (11.0), flor RmseLoss_BFI_temp(w1=0.05, w2=1.0)
    w2: 1.0
# USGS code.
target: ["00060_Mean"]    #, "00010_Mean"]#, "BFI_AVE"] #, "BFI_AVE", "PET"]     
tRange: [19800101, 20101001]   # This is the entire training/testing period (i.e., beginning of training to end of testing.)
# There should be an overlap because of the warm_up.
t_train: [19801001, 19951001]   #[20080101, 20230101]   
t_val: [20101001, 20111001]   #### Currently not used.
t_test: [19951001, 20101001]    #[19990101, 20080101]    # the first year is for warm_up
warm_up: 365
rho: 365
batch_size: 100   #208 
EPOCHS: 100    #5
hidden_size: 256
dropout: 0.5
saveEpoch: 2
no_basins: 25   # Number of basins sampled in each testing batch.
varT_NN: ['prcp(mm/day)', 'tmean(C)', 'dayl(s)', "PET_hargreaves(mm/day)
"]   # 'dayl(s)', , 'tmin(C)', 'vp(Pa)','srad(W/m2)', pet_nldas

## GAGESII dataset attributes. Use these for full 671 CAMELS Basins.
varC_NN: [
  'ELEV_MEAN_M_BASIN',  'ELEV_STD_M_BASIN',
  'SLOPE_PCT', 'DRAIN_SQKM', 'NDAMS_2009', 'MAJ_NDAMS_2009',
  'FRAGUN_BASIN', 'FORESTNLCD06',  'AWCAVE', 'PERMAVE', 'BDAVE',
  'ROCKDEPAVE', 'CLAYAVE', 'SILTAVE', 'SANDAVE', 'HGA', 'HGB',
  'HGC', 'HGVAR', 'HGD', 'PPTAVG_BASIN', 'SNOW_PCT_PRECIP',
  'PRECIP_SEAS_IND', 'T_AVG_BASIN',  'T_MAX_BASIN',
  'T_MAXSTD_BASIN', 'RH_BASIN',
  'GEOL_REEDBUSH_DOM_PCT', 'GEOL_REEDBUSH_DOM',
   'HIRES_LENTIC_PCT', 'PERDUN', 'PERHOR', 'RIP100_FOREST'

## CAMELS dataset attributes. Use these for the SN-Temp-complete 415 CAMELS basins.
#  'p_mean', 'pet_mean', 'p_seasonality', 'frac_snow', 'aridity',
#  'high_prec_freq', 'high_prec_dur', 'low_prec_freq', 'low_prec_dur',
#  'elev_mean', 'slope_mean', 'area_gages2', 'frac_forest', 'lai_max',
#  'lai_diff', 'gvf_max', 'gvf_diff', 'dom_land_cover_frac',
#  'dom_land_cover', 'root_depth_50', 'soil_depth_pelletier',
#  'soil_depth_statsgo', 'soil_porosity', 'soil_conductivity',
#  'max_water_content', 'sand_frac', 'silt_frac', 'clay_frac',
#  'geol_1st_class', 'glim_1st_class_frac', 'geol_2nd_class',
#  'glim_2nd_class_frac', 'carbonate_rocks_frac', 'geol_porostiy',
#  'geol_permeability'
]

### process based stream temperature model configuration
temp_model_name: "None"       #   "None" means no temperature model, "SNTEMP"
routing_temp_model: True
res_time_type: "SNTEMP"   #"van Vliet"  # "van Vliet", "Meisner", "SNTEMP"
res_time_lenF_ssflow: 30   #60
res_time_lenF_gwflow: 365 #
res_time_lenF_srflow: 1
lat_temp_adj: False
shade_smoothening: False
frac_smoothening_mode: False
frac_smoothening_gw_filter_size: 40
frac_smoothening_ss_filter_size: 40
STemp_default_emissivity_veg: 0
STemp_default_albedo: 0.1
STemp_default_delta_Z: 1.0    # for streambed conduction
params_water_density: 1000
params_C_w: 4184    # J/kg. K
NEARZERO: 1e-10
Epan_coef: 1.0
initial_values_shade_fraction: 0.1
varT_temp_model: ['tmax(C)', 'tmin(C)','dayl(s)', "t_monthly(C)", "ccov", "PET_hargreaves(mm/day)",
              'prcp(mm/day)', 'vp(Pa)', "srad(W/m2)", "dayofyear"]
varC_temp_model: ["area_gages2", "stream_length_square", 'PPTAVG_BASIN', 'SLOPE_PCT',
              'ELEV_MEAN_M_BASIN', "RIP100_FOREST", "lat"]    #  "area_gages2" (671 basin) == "DRAIN_SQKM" (415 basin)


### process based streamflow model configurations
hydro_model_name: "marrmot_PRMS"  # it can be marrmot_PRMS, HBV, SACSMA, or None -> "None" means no hydrology model
varT_hydro_model: ['prcp(mm/day)', 'tmax(C)', 'tmin(C)', "PET_hargreaves(mm/day)"] #, "t_monthly(C)", 'dayl(s)', "dayofyear"]    # , "pet_nldas"
varC_hydro_model: ['area_gages2', "lat"]    #  "area_gages2" (671 basin) == "DRAIN_SQKM" (415 basin)
routing_hydro_model: True

### PET model configurations
potet_module: "dataset" # "potet_hamon"  # "potet_hargreaves" , "dataset" -> Hamon is not ready beacause of lack of monthly coef
potet_dataset_name: "PET_hargreaves(mm/day)"  #"PET_hargreaves(mm/day)" # if "potet_module" == "dataset"

#srunoff_module: "srunoff_smidx"   # the nonlinear method, "srunoff_carea" linear method
#Dprst_flag: 1      # Dprst_flag = 1 means depression storage simulation is computed ( 0= no, 1 = yes)
#static_params_list_SNTEMP: [0,1,2,3,4,5, 6,7, 8, 9]
#semi_static_params_list_SNTEMP: []
#method_for_semi_static_param_SNTEMP: ["average", "average", "average", "average"]
#interval_for_semi_static_param_SNTEMP: [5, 5]
#static_params_list_prms: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17, 18, 19, 20]
#semi_static_params_list_prms: []
#method_for_semi_static_param_prms: ["average", "average", "average", "average"]
#interval_for_semi_static_param_prms: [30, 30]


